name: circular_selector
description: A widget which provides a new way of selecting values
version: 0.0.2
repository: "https://github.com/MatricalDefunkt/circular_selector"

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
